import Head from "next/head";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { Link } from "react-scroll";
import deved from "../public/avatar.png";
import thcredit from "../public/logo-thai-credit.jpeg";
import metro from "../public/metro.png";
import goingjesse from "../public/goingjesse.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by PEEM" />
        <link rel="icon" type="image/x-icon" href="code.png" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-700 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 -mb-12 flex justify-between dark:text-white">
            <div className="text-2xl flex justify-center gap-6 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/habonn">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/teerut-bunyarat-94aa38247/">
                <AiFillLinkedin />
              </a>
            </div>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="font-burtons text-4xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-4xl">
              Teerut Bunyarat
            </h2>
            <h3 className="text-md py-2 dark:text-white md:text-md">
              Front-End Developer
            </h3>
            <p className="text-sm italic py-5 leading-12 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-sm">
              Hi, I’m Peem! I’m a web developer. In a nutshell, I create
              websites that help organizations address business challenges and
              meet their needs. My expertise lies within front-end web apps, and
              the main languages in my tech stack are JavaScript, React, and of
              course HTML/CSS.
              {/* <Link
                to="experience"
                spy={true}
                smooth={true}
                offset={0}
                duration={300}
                className="text-teal-500 hover:cursor-pointer"
              >
                {" "}
                Work Experience!!!
              </Link> */}
            </p>
            <div></div>
            <div className="text-sm italic flex justify-center gap-4 py-1 text-teal-400 dark:text-white">
              <Link
                to="tech"
                spy={true}
                smooth={true}
                offset={0}
                duration={300}
                className="text-teal-500 hover:cursor-pointer"
              >
                {" "}
                Technology
              </Link>
              <span>|</span>
              <Link
                to="education"
                spy={true}
                smooth={true}
                offset={0}
                duration={300}
                className="text-teal-500 hover:cursor-pointer"
              >
                {" "}
                Education
              </Link>
              <span>|</span>
              <Link
                to="experience"
                spy={true}
                smooth={true}
                offset={0}
                duration={300}
                className="text-teal-500 hover:cursor-pointer"
              >
                {" "}
                Experience
              </Link>
            </div>
            <div className="xs:mx-auto -ml-20 from-teal-500 rounded-full w-80 h-80 dark:shadow-[80px_0px_0px_8px_rgba(255,255,0)] relative overflow-hidden mt-5 md:h-93 md:w-93">
              <Image
                src={deved}
                alt="pic-peem"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </section>
        <section id="tech" className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              TECHNOLOGIES AND LANGUAGES
            </h3>
            <hr className="border-[#a9a9a9] mb-2 mt-0"></hr>
            <ul class="text-left list-disc pl-8 dark:text-white">
              <li>
                <span class="w-28 inline-block dark:text-teal-500">
                  Languages:
                </span>{" "}
                <span>JavaScript, Node.js, Java, SQL, PHP, CSS, HTML</span>{" "}
              </li>
              <li>
                <span class="w-28 inline-block dark:text-teal-500">
                  Frameworks:
                </span>{" "}
                <span>
                  ReactJS, AngularJS, React-Native, NextJS, TailwindCSS,
                  Bootstrap, Ant-design, Material-UI
                </span>{" "}
              </li>
              <li>
                <span class="w-28 inline-block dark:text-teal-500">Tools:</span>{" "}
                <span>
                  Git, Docker, Zsh, GitHub, MobX, Jira, Sourcetree, Ansible{" "}
                </span>{" "}
              </li>
              <li>
                <span class="w-28 inline-block dark:text-teal-500">Other:</span>{" "}
                <span>
                  Linux, AWS, GCP, Vercel, DigitalOcean, Heroku, Wordpress,
                  Microsoft products
                </span>{" "}
              </li>
            </ul>
          </div>
        </section>
        <section id="education">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">EDUCATION</h3>
            <hr className="border-[#a9a9a9] mb-2 mt-0"></hr>
            <ul class="text-left list-disc pl-8">
              <li className="dark:text-white">
                <strong className="dark:text-teal-500">
                  {" "}
                  B.Sc. Information Technology
                </strong>
                ,<span> Burapha University, TH. 2016-2020 (GPA 3.35)</span>{" "}
              </li>
            </ul>
          </div>
        </section>
        <section id="experience" className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">WORK EXPERIENCE</h3>
            <hr className="border-[#a9a9a9] mb-2 mt-0"></hr>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a web developer, I’ve done
              remote work for
              <span className="text-teal-500"> agencies </span>
              develop for <span className="text-teal-500">organizations </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
          </div>
          <div className="antialiased text-gray-800">
            <div className="relative container mx-auto px-6 flex flex-col space-y-8">
              <div className="absolute z-0 w-2 h-full bg-white dark:bg-[rgba(205,205,205,1)] shadow-md inset-0 left-17 md:mx-auto md:right-0 md:left-0"></div>
              <div className="relative z-10">
                <div className="timeline-img">
                  <Image
                    src={thcredit}
                    alt={"thai-credit"}
                    className="timeline-img"
                  />
                </div>
                <div className="timeline-container">
                  <div className="timeline-point" aria-hidden="true"></div>
                  <div className="bg-white p-6  rounded-md shadow-md bg-gradient-to-b from-teal-500">
                    <span className="font-bold text-white text-sm tracking-wide">
                      May 2022 to Present
                    </span>
                    <h1 className="text-2xl font-bold pt-1">
                      <span> Thai Credit Retail Bank</span>
                      <span className="text-lg font-normal">
                        , Bangkok, Thailand
                      </span>{" "}
                    </h1>
                    <h3 className="px-2 text-white bg-gradient-to-r from-blue-400 rounded">
                      Front-End Developer
                    </h3>
                    <ul class="text-left list-disc pl-8">
                      <li>
                        Developed backoffice web applications using reactjs,
                        nextjs for use with users within banking organizations.
                      </li>
                      <li>
                        Optimized and supported on backoffice project to reduce
                        problems.
                      </li>
                      <li>
                        Collaborated with the backend team to construct &
                        optimize various complex algorithms improving
                        performance.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="relative z-10">
                <div className="timeline-img">
                  <Image
                    src={metro}
                    width={93}
                    height={93}
                    alt={"metro1"}
                    className="rounded-full"
                  />
                </div>
                <div className="timeline-container timeline-container-left">
                  <div
                    className="timeline-point timeline-pointer-left"
                    aria-hidden="true"
                  ></div>

                  <div className="bg-white p-6  rounded-md shadow-md bg-gradient-to-b from-teal-500">
                    <span className="font-bold text-white text-sm tracking-wide">
                      Jan 2021 to Apr 2022
                    </span>
                    <h1 className="text-2xl font-bold pt-1">
                      <span> Metro Systems</span>
                      <span className="text-lg font-normal">
                        , Bangkok, Thailand
                      </span>{" "}
                    </h1>
                    <h3 className="px-2 text-white bg-gradient-to-r from-blue-400 rounded">
                      Front-End Developer
                    </h3>
                    <ul class="text-left list-disc pl-8">
                      <li>
                        Designed & developed to create a reservation web
                        application for organizations using angularjs connected
                        with sharepoint.
                      </li>
                      <li>
                        Optimized the old project through the reduction of
                        unnecessary calls to the back-end from sharepoint inturn
                        reducing startup time.
                      </li>
                      <li>
                        Research work with new microsoft product for supported
                        organizations E.g. Share point, Viva, Power Apps, Power
                        BI
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="relative z-10">
                <div className="timeline-img">
                  <Image
                    src={goingjesse}
                    width={93}
                    height={93}
                    alt={"going"}
                    className="rounded-full"
                  />
                </div>
                <div className="timeline-container">
                  <div className="timeline-point" aria-hidden="true"></div>
                  <div className="bg-white p-6  rounded-md shadow-md bg-gradient-to-b from-teal-500">
                    <span className="font-bold text-white text-sm tracking-wide">
                      Jul 2020 to Oct 2020
                    </span>
                    <h1 className="text-2xl font-bold pt-1">
                      <span> Goingjesse</span>
                      <span className="text-lg font-normal">
                        , Bangkok, Thailand
                      </span>{" "}
                    </h1>
                    <h3 className="px-2 text-white bg-gradient-to-r from-blue-400 rounded">
                      Front-End Developer
                    </h3>
                    <ul class="text-left list-disc pl-8">
                      <li>
                        Designed and implemented a web-based application to
                        provide KPI systems.
                      </li>
                      <li>
                        Created new features, functionality and capabilities on
                        the KPI systems sites using crystal report with react
                        component.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="relative z-10">
                <div className="timeline-img">
                  <Image
                    src={metro}
                    width={93}
                    height={93}
                    alt={"metro-2"}
                    className="rounded-full"
                  />
                </div>
                <div className="timeline-container timeline-container-left">
                  <div
                    className="timeline-point timeline-pointer-left"
                    aria-hidden="true"
                  ></div>

                  <div className="bg-white p-6  rounded-md shadow-md bg-gradient-to-b from-teal-500">
                    <span className="font-bold text-white text-sm tracking-wide">
                      Dec 2019 to Mar 2020
                    </span>
                    <h1 className="text-2xl font-bold pt-1">
                      <span> Metro Systems</span>
                      <span className="text-lg font-normal">
                        , Bangkok, Thailand
                      </span>{" "}
                    </h1>
                    <h3 className="px-2 text-white bg-gradient-to-r from-blue-400 rounded">
                      Front-End Developer, Internship
                    </h3>
                    <ul class="text-left list-disc pl-8">
                      <li>
                        Designed & developed an customer service application web
                        and mobile for technician project for graduated with
                        reactjs and react native.
                      </li>
                      <li>
                        Developed an interactive map for a customer service app
                        project and show on features in web and mobile.
                      </li>
                      <li>
                        Designed front-end code using reactjs and material ui to
                        created a responsive web application that works cross
                        desktops, tablets and 20+ other device.
                      </li>
                      <li>
                        Assisted in developed a new project CRM of company in
                        front-end with react and research problems with the
                        systems.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
